"""Add Roles for user

Revision ID: 86676139cd76
Revises: cb866ccae890
Create Date: 2026-05-12 02:02:20.656658

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "86676139cd76"
down_revision: Union[str, Sequence[str], None] = "cb866ccae890"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    role_enum = sa.Enum("admin", "user", name="role")
    role_enum.create(op.get_bind())

    op.add_column("user", sa.Column("role", role_enum, nullable=True))

    op.execute("UPDATE \"user\" SET role = 'user' WHERE role IS NULL")

    op.alter_column("user", "role", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    # ### end Alembic commands ###
